name: build

on: [push, pull_request]

env:
  DEFAULT_PYTHON_VERSION: "3.11"

jobs:
  test:
    strategy:
      matrix:
        os:
          - name: Linux
            type: ubuntu-latest
          - name: macOS
            type: macOS-latest
          - name: Windows
            type: windows-latest
        haskell:
          - ghc:
              version: "9.2"
          - cabal:
              version: "3.6"

    name: ${{ matrix.os.name }} / GHC-${{ matrix.haskell.ghc.version }} - Python ${{ env.DEFAULT_PYTHON_VERSION }}
    runs-on: ${{ matrix.os.type }}
    env:
      OUTPUT_DIRECTORY: .cache
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Setup Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create project from template
        run: cookiecutter --no-input -o ${{ env.OUTPUT_DIRECTORY }} . project_slug=haskell-boilerplate fullname="Wen Kokke" email="wenkokke@users.noreply.github.com" github="wenkokke" use_git_init=n ghc_version="${{ matrix.ghc-version }}" cabal_version="${{ matrix.cabal-version }}" use_pre_commit=n use_test=y

      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.haskell.ghc.version }}
          cabal-version: ${{ matrix.haskell.cabal.version }}

      - name: Test project
        run: |
          cabal v2-update
          cabal v2-test
        working-directory: ${{ env.OUTPUT_DIRECTORY }}/haskell-boilerplate
