name: Test

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        ghc-version: ["9.2.4"]
        cabal-version: ["3.6.2.0"]
        python-version: ["3.10"]
        include:
          - os: ubuntu-latest
            python-version: "3.7"
          - os: ubuntu-latest
            python-version: "3.8"
          - os: ubuntu-latest
            python-version: "3.9"
    name: Test on ${{ matrix.os }} with GHC-${{ matrix.ghc-version }} and Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "requirements-ci.txt"

      - name: Setup Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements-ci.txt

      - name: Create project from template
        run: cookiecutter --no-input -o ${{ runner.temp }} . git_init=n github=${{ github.actor }} project_slug=haskell-boilerplate ghc_version=${{ matrix.ghc-version }} cabal_version=${{ matrix.cabal-version }}

      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc-version }}
          cabal-version: ${{ matrix.cabal-version }}

      - name: Test project
        run: |
          cd ${{ runner.temp }}/haskell-boilerplate
          cabal v2-test
