name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        ghc-version: ["9.2.4"]
        cabal-version: ["3.6.2.0"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          pipx cookiecutter --no-input --output-dir ${{ env.RUNNER_TEMP }} . ghc_version=${{ matrix.ghc-version }} cabal_version=${{ matrix.cabal-version }}
          cd ${{ env.RUNNER_TEMP }}/haskell-boilerplate
          cabal v2-test